# Generated by Django 5.0.6 on 2024-06-17 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3595eaf7-c4fb-4550-9c29-c065f7a6c0f9'), editable=False, primary_key=True, serialize=False, verbose_name='uid'),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('d88383b2-2ba5-4857-9679-1fc8ff69865c'), editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
